import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import styled from "@emotion/styled";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main
      // className={styles.main}
      >
        <CustomSection>1</CustomSection>
        <CustomSection className="second">2</CustomSection>
        <CustomSection>3</CustomSection>
      </Main>
    </>
  );
}

const Main = styled.div`
  position: relative;
  height: 100vh;
  overflow: auto;
  scroll-snap-type: y mandatory;
`;

const CustomSection = styled.section`
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
  scroll-snap-align: center;

  font-family: sans-serif;
  background: #fed0d1;
  color: #f34a4e;
  font-weight: bold;
  text-transform: uppercase;
  letter-spacing: 0.1em;

  &.second {
    background: #f34a4e;
    color: #fed0d1;
  }
`;
