import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import styled from "@emotion/styled";
import {
  FirstSection,
  SecondSection,
  ThirdSection,
  FourthSection,
} from "@components/pages/Main";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main
      // className={styles.main}
      >
        <FirstSection />
        <SecondSection />
        <ThirdSection />
        <FourthSection />
      </Main>
    </>
  );
}

const Main = styled.div`
  position: relative;
  width: 100%;
  max-width: 1920px;
  height: 100vh;
  overflow: auto;
  border: 1px solid black;

  &::-webkit-scrollbar {
    display: none;
  }
  scroll-snap-type: y mandatory;
`;
