import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import styled from "@emotion/styled";
import { FirstSection, ForthSection } from "@components/pages/Main";
import SecondSection from "@components/pages/Main/SecondSection.component";
import ThirdSection from "@components/pages/Main/ThirdSection.component";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main
      // className={styles.main}
      >
        <FirstSection />
        <SecondSection />
        <ThirdSection />
        <ForthSection />
      </Main>
    </>
  );
}

const Main = styled.div`
  position: relative;
  width: 100%;
  max-width: 1920px;
  height: 100vh;
  overflow: auto;
  border: 1px solid black;

  &::-webkit-scrollbar {
    display: none;
  }
  scroll-snap-type: y mandatory;
`;

const CustomSection = styled.section`
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
  scroll-snap-align: center;

  font-family: sans-serif;
  background: #fed0d1;
  color: #f34a4e;
  font-weight: bold;
  text-transform: uppercase;
  letter-spacing: 0.1em;

  &.second {
    background: #f34a4e;
    color: #fed0d1;
  }
`;
